#ifndef _CONSTANTS_HPP_
#define _CONSTANTS_HPP_

#define NUMBER_OF_STEPS 3
#define GALLERY1_MAX_OCCUPANCY 5
#define GLASS_CORRIDOR_MAX_OCCUPANCY 3

#define STANDARD_TICKET_START_ID 1001
#define STANDARD_TICKET_END_ID 1100
#define PREMIUM_TICKET_START_ID 2001
#define PREMIUM_TICKET_END_ID 2100

#define LAMDA 10000.234

#endif // _CONSTANTS_HPP_

